package com.smrtgrdyn.smrtgrdyn.Garden.Notifications;

import javax.persistence.*;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.UUID;

@Entity
@Table(name = "notification_table")
@IdClass(NotificationId.class)
public class Notification {

    @Id
    UUID gardenId;
    @Id
    Timestamp timestamp;

    @Column(nullable = false)
    String type;

    //Generated By Construction
    String message;

    public Notification() {
    }

    public Notification(UUID gardenId, Timestamp timestamp, String type) {
        this.gardenId = gardenId;
        this.timestamp = timestamp;
        this.type = type;
        this.message = generateMessage(this.type);
    }

    public UUID getGardenId() {
        return gardenId;
    }

    public void setGardenId(UUID gardenId) {
        this.gardenId = gardenId;
    }

    public Timestamp getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String generateMessage(String type){

        StringBuilder sb = new StringBuilder("A");

        switch (type){
            case "animal":
                sb.append("n animal was detected at")
                        .append(new SimpleDateFormat("HH:mm MM/dd/yyyy").format(this.timestamp));
                break;
            case "leak":
                sb.append(" leak was detected at")
                        .append(new SimpleDateFormat("HH:mm MM/dd/yyyy").format(this.timestamp))
                        .append("\nReason: Water Flow Detected when Water Valve was turned off.");
        }


        return sb.toString();
    }
    @Override
    public String toString() {
        return "Notification{" +
                "gardenId=" + gardenId +
                ", timestamp=" + timestamp +
                ", type='" + type + '\'' +
                ", message='" + message + '\'' +
                '}';
    }
}
